service: slss-workshop

custom:
  bucket: <bucket name>

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:getObject
      Resource: "arn:aws:s3:::${self:custom.bucket}/*"

functions:
  postprocess:
    handler: handler.postprocess
    environment:
      SLACKWEBHOOK: <webhook url>
    events:
      - s3:
          bucket: ${self:custom.bucket}
          event: s3:ObjectCreated:*
